### ISSUE TITLE
General Bugs and Feedback

### ISSUE THREAD

**Issue by MTCGIS** [BayAreaMetro/basis#1]
General (East Palo Alto, Chrome, PC):
•	When I clicked on the Register button, a spinning wheel appeared and then disappeared and the page didn’t change. It was hard to tell if the form went through and so I was tempted to click Register again…and again…and again… but I didn’t.
•	It might be helpful to let users know that they may have to hit refresh for things to show up. I first noticed this when adding or changing a new zoning code and had to hit refresh for it to show up, but it sometimes happens in other places
•	For user instructions, keep in mind that the name “Tools” shows up as a dropdown in the menu bar at top AND as a column header in the Action Items. For example, I thought  “Click Review under tools to review data items” meant the Tools dropdown menu at the top right at first. Either make this clear in directions or change one of the names.

**Comment by mziyambi** [comment]
Issues have been addressed. Continue to monitor for registration.
