### ISSUE TITLE
Add Description for Development Policies

### ISSUE THREAD

**Issue by Keareys** [BayAreaMetro/BASIS#14]

**Comment by joshuacroff** [comment]
@Keareys: I've added the following description for development policies: "Development Policies are laws, rules, processes, fees, and subsidies that impact private sector real estate development. Common policies for a parcel or neighborhood might limit uses (e.g., no commercial uses allowed), set maximum intensities (e.g., no more than 10 dwelling units per acre), require multiple project approvals, or assess fees on construction. All together, these policies influence project feasibility at a site to the extent that profitable projects may become unprofitable and vice versa. In this way they play a major role in determining the future trajectory of Bay Area neighborhoods."
