### ISSUE TITLE
Buttons on Data Details Page not Displaying Correctly

### ISSUE THREAD

**Issue by joshuacroff** [BayAreaMetro/BASIS#29]
@mziyambi & @Keareys: there appears to be an issue with how the buttons are rendering on the data details pages for datasets where these buttons are present. I'm also noticing a black box being displayed at the bottom of the upload page. May be a related issue. 
![screen shot 2018-08-06 at 4 08 47 pm](https://user-images.githubusercontent.com/6758853/43745443-970466b4-9993-11e8-9ad1-0dad12d46972.png)
![screen shot 2018-08-06 at 4 13 21 pm](https://user-images.githubusercontent.com/6758853/43745458-ac0e15b4-9993-11e8-9972-ae6dd42e1052.png)

**Comment by Keareys** [comment]
Fixed
