### ISSUE TITLE
Add Description and Type attributes to Non-Developable Sites table

### ISSUE THREAD

**Issue by dgbay** [BayAreaMetro/BASIS#32]
Please add a Description field and a Type field to the Non-Developable Sites table.This is really two separate requests, bundled because they are related.  

As we are asking humans to inspect and update the non-developable sites data, we need a human readable description.  I suggest this be a relatively short text field for phrases like "Mills Hospital" rather that unlimited text (which could attract long descriptions).  

As we talk about and use this dataset an implicit typology has emerged--separate layers if you will.  I believe it will be useful to have picklist field that allows us to reflect that typology.  Geographical features, with subtypes for wetlands, slopes, etc.  Publicly versus Privately owned public-serving or institutional uses such as golf courses, libraries, hospitals.   Deed-restricted affordable housing (DRAH) sites. An additional reason for this is that certain types, for example DRAH may evolve into relatively discrete datasets with an elaborated and eventually standardize schema.

**Comment by joshuacroff** [comment]
Hey @dgbay: I've added these fields to the required fields for Non-Developable Sites.

**Comment by dgbay** [comment]
!!!!!!!    Thank you
