### ISSUE TITLE
Issues with East Palo Alto

### ISSUE THREAD

**Issue by MTCGIS** [BayAreaMetro/basis#4]
In the Map review (East Palo Alto, Chrome, PC): 
•	The first time I opened the zoning map for review, it didn’t show the parcels and colors. It only showed the base map. I closed the tab and clicked on the Review Data button again and it opened with the parcels showing.
•	There is no link under Focused Document.
•	When I clicked Cancel, the view reloaded to the Bay Area, not East Palo Alto, and did not show the EPA parcels anymore. I can’t get the parcels for EPA to show up anymore even after closing the Map tab and re-opening using the Review Data button
•	When I click on Reset Map, it shows the full Bay Area rather than showing the EPA extent
•	In the Zoning Map Review Checklist, why does it say “Checked” instead of “Reviewed” like it does everywhere else?

**Comment by mziyambi** [comment]
Map loading correctly with parcels symbolized.
No link exists for focused document. 
Cancel/Reset map now reloads the page. 
Checklist updated to Reviewed
