### ISSUE TITLE
Foster City Zoning Map is Missing in link

### ISSUE THREAD

**Issue by Keareys** [BayAreaMetro/BASIS#63]
We should be sure to download all PDFs if we can.

**Comment by Keareys** [comment]
The URL Link for this jurisdiction is malformed.  There are two urls in one column/row for this entry:

The URL should look like - https://www.fostercity.org/sites/default/files/fileattachments/community_development/page/3421/3-4-land-use.pdf

Instead it looks like:
https://www.fostercity.org/sites/default/files/fileattachments/community_development/page/3421/3-4-land-use.pdfhttps://www.google.com/maps/d/viewer?mid=1E27c_loPs9-ArDWnDXVlq5XAueA&ll=37.55835434556453%2C-122.27280714819341&z=16

There are two url above:
https://www.fostercity.org/sites/default/files/fileattachments/community_development/page/3421/3-4-land-use.pdf

https://www.google.com/maps/d/viewer?mid=1E27c_loPs9-ArDWnDXVlq5XAueA&ll=37.55835434556453%2C-122.27280714819341&z=16

**Comment by joshuacroff** [comment]
@Keareys I've fixed this issue.
