### ISSUE TITLE
General Plan Land Use Lookup Values have duplicates for some Jurisdictions

### ISSUE THREAD

**Issue by Keareys** [BayAreaMetro/BASIS#65]
While reviewing the GP Land Use Codes by Jurisdiction, I discovered duplicate rows for some jurisdictions Land Use Codes.  In some cases these duplicates have the same UUID, and in some other cases they have different UUIDs.  We need to remove all duplicates and ensure that we are not breaking the links for any values that have already been assigned.  I suggest we extract all duplicates into a separate table and only leave the unique values in the primary lookup table.

We can discuss further when we are ready to fix this issue.

**Comment by joshuacroff** [comment]
Duplicate issue resolved. Duplicates were occurring due to updates to table being appended rather than replacing the table in Socrata when updates were made to the table.
