### ISSUE TITLE
Make the upload tool a modal window that opens on any page that the link clicks onto.

### ISSUE THREAD

**Issue by Keareys** [BayAreaMetro/BASIS#8]
This tool will also need to be a accessed from the Survey.  If you look at a few of the Survey pages, you’ll see the word Link on the survey which is meant to access the upload tool.  Duane has a fairly detailed way that he would like the data to be uploaded onto AWS S3 in folders for the jurisdiction, and survey question that they are responding to.  We will probably need to talk more about this feature as it is a bit complicated.

**Comment by mziyambi** [comment]
Left as a standalone page for now.
